# libunistring-dev

export LC_ALL=C

all:
	gcc test.c -static ../.lib/x86_64-linux-gnu/libcurl.a  -lidn2 -lssl -lcrypto -lz -ltasn1 -lunistring -lgmp -lcrypto -lpthread -ldl

ok:
	gcc test.c -static ../.lib/x86_64-linux-gnu/libcurl.a  -lidn2 -lssl -lcrypto -lz -ltasn1 -lunistring -lgmp -lcrypto -lpthread -ldl

